#-*- coding:utf-8 -*-
字符集 = 'M@N%W$E#RK&FXYI*l]}1/+i>"!~\';,`:.'
背景图片 = 'background.png'
缩放倍数 = 0.5
比特数 = 8
演示模式 = 0
图片路径 = 'G:/university/MyAI project/py files/other py files/ascii_converter/previews/2.jpg'
视频帧图路径 = None
视频路径 = None
视频帧图片保存路径 = None
视频导出帧图片到文件夹 = False
导出视频 = True
颜色 = (0, 0, 0, 255)
帧数 = 1000
视频转换帧数区间 = (0, 300)
字符画保存为图片 = False
屏幕宽度 = 1200
屏幕高度 = 700
字符画保存为文本文件 = True
显示转换进度 = True
fps = 30
font_path = None
font_size = 10
width_resize = 1
height_resize = 1
输出图片为彩色 = False
